### ISSUE TITLE
Проектная часть 4 lab - Проектирование API Gateway

### ISSUE THREAD

**Issue by OrangeFlag** [OrangeFlag/itmo-microservice#14]
* Описание последовательности действий (в виде соответствующий UML диаграммы) взаимодействия сервисов через API Gateway для каждой из заданных в условии операций, вовлекающих в исполнение более одного сервиса.
* Описание должно включать как позитивные сценарии, так и покрывать случаи исключительных ситуаций
* Проектирование как минимум одного запроса, требующего получать и агрегировать (создавать новую структуру данных на основе полученных данных) данные из более чем одного сервиса

**Comment by HiddenTreasure525** [comment]
Спроектировано, в отчете
