### ISSUE TITLE
Ручное тестирование

### ISSUE THREAD

**Issue by OrangeFlag** [OrangeFlag/itmo-microservice#19]
Подергать endpoint в нормальных режимах, с граничными значениями и некорректными входными данными
Поведение должно соответсовать описанному в [API](https://docs.google.com/document/d/1FKO65Ga0rRVPVArQERqO__3fkOeCWFGgSKRb6_tCX9U/edit#)

**Comment by OrangeFlag** [comment]
Проверка работоспособности (здесь речь скорее о правильной обработке частичных падений и т.д.) при отсутствии работающих экземпляров каждого из сервисов.

**Comment by OrangeFlag** [comment]
orders
addItem создает каждый раз новый продукт, хотя должен добавлять в тот же, если id совпадает

**Comment by OrangeFlag** [comment]
Hybernate пересоздает таблицы при запуске

**Comment by HiddenTreasure525** [comment]
Пофикшено, исправлено
